default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: true
  host: localhost
  username: root
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  port: 3306
  checkout_timeout: 5

development:
  <<: *default
  database: greetings_development

test:
  <<: *default
  database: greetings_test

production:
  <<: *default
  database: greetings_production
